/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsListIdRouteImport } from './routes/lists/$listId'
import { Route as ApiPurchasesIndexRouteImport } from './routes/api/purchases/index'
import { Route as ApiListsIndexRouteImport } from './routes/api/lists/index'
import { Route as ApiItemsIndexRouteImport } from './routes/api/items/index'
import { Route as ApiCategoriesIndexRouteImport } from './routes/api/categories/index'
import { Route as ApiListsSplatRouteImport } from './routes/api/lists/$'
import { Route as ApiItemsSplatRouteImport } from './routes/api/items/$'
import { Route as ApiCategoriesSplatRouteImport } from './routes/api/categories/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiListsItemsIndexRouteImport } from './routes/api/lists/items/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => ListsRoute,
} as any)
const ApiPurchasesIndexRoute = ApiPurchasesIndexRouteImport.update({
  id: '/api/purchases/',
  path: '/api/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsIndexRoute = ApiListsIndexRouteImport.update({
  id: '/api/lists/',
  path: '/api/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsIndexRoute = ApiItemsIndexRouteImport.update({
  id: '/api/items/',
  path: '/api/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIndexRoute = ApiCategoriesIndexRouteImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsSplatRoute = ApiListsSplatRouteImport.update({
  id: '/api/lists/$',
  path: '/api/lists/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsSplatRoute = ApiItemsSplatRouteImport.update({
  id: '/api/items/$',
  path: '/api/items/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesSplatRoute = ApiCategoriesSplatRouteImport.update({
  id: '/api/categories/$',
  path: '/api/categories/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsItemsIndexRoute = ApiListsItemsIndexRouteImport.update({
  id: '/api/lists/items/',
  path: '/api/lists/items/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/items': typeof ItemsRoute
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$': typeof ApiCategoriesSplatRoute
  '/api/items/$': typeof ApiItemsSplatRoute
  '/api/lists/$': typeof ApiListsSplatRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/items/': typeof ApiItemsIndexRoute
  '/api/lists/': typeof ApiListsIndexRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/lists/items/': typeof ApiListsItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/items': typeof ItemsRoute
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$': typeof ApiCategoriesSplatRoute
  '/api/items/$': typeof ApiItemsSplatRoute
  '/api/lists/$': typeof ApiListsSplatRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/items': typeof ApiItemsIndexRoute
  '/api/lists': typeof ApiListsIndexRoute
  '/api/purchases': typeof ApiPurchasesIndexRoute
  '/api/lists/items': typeof ApiListsItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/items': typeof ItemsRoute
  '/lists': typeof ListsRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/categories/$': typeof ApiCategoriesSplatRoute
  '/api/items/$': typeof ApiItemsSplatRoute
  '/api/lists/$': typeof ApiListsSplatRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/items/': typeof ApiItemsIndexRoute
  '/api/lists/': typeof ApiListsIndexRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/lists/items/': typeof ApiListsItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/items'
    | '/lists'
    | '/login'
    | '/signup'
    | '/lists/$listId'
    | '/api/auth/$'
    | '/api/categories/$'
    | '/api/items/$'
    | '/api/lists/$'
    | '/api/categories/'
    | '/api/items/'
    | '/api/lists/'
    | '/api/purchases/'
    | '/api/lists/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/items'
    | '/lists'
    | '/login'
    | '/signup'
    | '/lists/$listId'
    | '/api/auth/$'
    | '/api/categories/$'
    | '/api/items/$'
    | '/api/lists/$'
    | '/api/categories'
    | '/api/items'
    | '/api/lists'
    | '/api/purchases'
    | '/api/lists/items'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/items'
    | '/lists'
    | '/login'
    | '/signup'
    | '/lists/$listId'
    | '/api/auth/$'
    | '/api/categories/$'
    | '/api/items/$'
    | '/api/lists/$'
    | '/api/categories/'
    | '/api/items/'
    | '/api/lists/'
    | '/api/purchases/'
    | '/api/lists/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ItemsRoute: typeof ItemsRoute
  ListsRoute: typeof ListsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCategoriesSplatRoute: typeof ApiCategoriesSplatRoute
  ApiItemsSplatRoute: typeof ApiItemsSplatRoute
  ApiListsSplatRoute: typeof ApiListsSplatRoute
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiItemsIndexRoute: typeof ApiItemsIndexRoute
  ApiListsIndexRoute: typeof ApiListsIndexRoute
  ApiPurchasesIndexRoute: typeof ApiPurchasesIndexRoute
  ApiListsItemsIndexRoute: typeof ApiListsItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof ListsRoute
    }
    '/api/purchases/': {
      id: '/api/purchases/'
      path: '/api/purchases'
      fullPath: '/api/purchases/'
      preLoaderRoute: typeof ApiPurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/': {
      id: '/api/lists/'
      path: '/api/lists'
      fullPath: '/api/lists/'
      preLoaderRoute: typeof ApiListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/': {
      id: '/api/items/'
      path: '/api/items'
      fullPath: '/api/items/'
      preLoaderRoute: typeof ApiItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories/'
      preLoaderRoute: typeof ApiCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/$': {
      id: '/api/lists/$'
      path: '/api/lists/$'
      fullPath: '/api/lists/$'
      preLoaderRoute: typeof ApiListsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$': {
      id: '/api/items/$'
      path: '/api/items/$'
      fullPath: '/api/items/$'
      preLoaderRoute: typeof ApiItemsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$': {
      id: '/api/categories/$'
      path: '/api/categories/$'
      fullPath: '/api/categories/$'
      preLoaderRoute: typeof ApiCategoriesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/items/': {
      id: '/api/lists/items/'
      path: '/api/lists/items'
      fullPath: '/api/lists/items/'
      preLoaderRoute: typeof ApiListsItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ListsRouteChildren {
  ListsListIdRoute: typeof ListsListIdRoute
}

const ListsRouteChildren: ListsRouteChildren = {
  ListsListIdRoute: ListsListIdRoute,
}

const ListsRouteWithChildren = ListsRoute._addFileChildren(ListsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ItemsRoute: ItemsRoute,
  ListsRoute: ListsRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCategoriesSplatRoute: ApiCategoriesSplatRoute,
  ApiItemsSplatRoute: ApiItemsSplatRoute,
  ApiListsSplatRoute: ApiListsSplatRoute,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiItemsIndexRoute: ApiItemsIndexRoute,
  ApiListsIndexRoute: ApiListsIndexRoute,
  ApiPurchasesIndexRoute: ApiPurchasesIndexRoute,
  ApiListsItemsIndexRoute: ApiListsItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
