/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as ListsListIdRouteImport } from './routes/lists/$listId'
import { Route as ApiPurchasesIndexRouteImport } from './routes/api/purchases/index'
import { Route as ApiListsIndexRouteImport } from './routes/api/lists/index'
import { Route as ApiItemsIndexRouteImport } from './routes/api/items/index'
import { Route as ApiCategoriesIndexRouteImport } from './routes/api/categories/index'
import { Route as ApiUserLocationRouteImport } from './routes/api/user/location'
import { Route as ApiLocationsProvincesRouteImport } from './routes/api/locations/provinces'
import { Route as ApiLocationsCitiesRouteImport } from './routes/api/locations/cities'
import { Route as ApiListsSplatRouteImport } from './routes/api/lists/$'
import { Route as ApiItemsSplatRouteImport } from './routes/api/items/$'
import { Route as ApiCategoriesSplatRouteImport } from './routes/api/categories/$'
import { Route as ApiCatalogPriceRouteImport } from './routes/api/catalog/price'
import { Route as ApiCatalogItemsRouteImport } from './routes/api/catalog/items'
import { Route as ApiCatalogCategoriesRouteImport } from './routes/api/catalog/categories'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiListsItemsIndexRouteImport } from './routes/api/lists/items/index'
import { Route as ApiListsItemsAddRouteImport } from './routes/api/lists/items/add'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchasesIndexRoute = ApiPurchasesIndexRouteImport.update({
  id: '/api/purchases/',
  path: '/api/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsIndexRoute = ApiListsIndexRouteImport.update({
  id: '/api/lists/',
  path: '/api/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsIndexRoute = ApiItemsIndexRouteImport.update({
  id: '/api/items/',
  path: '/api/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesIndexRoute = ApiCategoriesIndexRouteImport.update({
  id: '/api/categories/',
  path: '/api/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserLocationRoute = ApiUserLocationRouteImport.update({
  id: '/api/user/location',
  path: '/api/user/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsProvincesRoute = ApiLocationsProvincesRouteImport.update({
  id: '/api/locations/provinces',
  path: '/api/locations/provinces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationsCitiesRoute = ApiLocationsCitiesRouteImport.update({
  id: '/api/locations/cities',
  path: '/api/locations/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsSplatRoute = ApiListsSplatRouteImport.update({
  id: '/api/lists/$',
  path: '/api/lists/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsSplatRoute = ApiItemsSplatRouteImport.update({
  id: '/api/items/$',
  path: '/api/items/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesSplatRoute = ApiCategoriesSplatRouteImport.update({
  id: '/api/categories/$',
  path: '/api/categories/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogPriceRoute = ApiCatalogPriceRouteImport.update({
  id: '/api/catalog/price',
  path: '/api/catalog/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogItemsRoute = ApiCatalogItemsRouteImport.update({
  id: '/api/catalog/items',
  path: '/api/catalog/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogCategoriesRoute = ApiCatalogCategoriesRouteImport.update({
  id: '/api/catalog/categories',
  path: '/api/catalog/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsItemsIndexRoute = ApiListsItemsIndexRouteImport.update({
  id: '/api/lists/items/',
  path: '/api/lists/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiListsItemsAddRoute = ApiListsItemsAddRouteImport.update({
  id: '/api/lists/items/add',
  path: '/api/lists/items/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/lists/': typeof ListsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/categories': typeof ApiCatalogCategoriesRoute
  '/api/catalog/items': typeof ApiCatalogItemsRoute
  '/api/catalog/price': typeof ApiCatalogPriceRoute
  '/api/categories/$': typeof ApiCategoriesSplatRoute
  '/api/items/$': typeof ApiItemsSplatRoute
  '/api/lists/$': typeof ApiListsSplatRoute
  '/api/locations/cities': typeof ApiLocationsCitiesRoute
  '/api/locations/provinces': typeof ApiLocationsProvincesRoute
  '/api/user/location': typeof ApiUserLocationRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/items/': typeof ApiItemsIndexRoute
  '/api/lists/': typeof ApiListsIndexRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/lists/items/add': typeof ApiListsItemsAddRoute
  '/api/lists/items/': typeof ApiListsItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/lists': typeof ListsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/categories': typeof ApiCatalogCategoriesRoute
  '/api/catalog/items': typeof ApiCatalogItemsRoute
  '/api/catalog/price': typeof ApiCatalogPriceRoute
  '/api/categories/$': typeof ApiCategoriesSplatRoute
  '/api/items/$': typeof ApiItemsSplatRoute
  '/api/lists/$': typeof ApiListsSplatRoute
  '/api/locations/cities': typeof ApiLocationsCitiesRoute
  '/api/locations/provinces': typeof ApiLocationsProvincesRoute
  '/api/user/location': typeof ApiUserLocationRoute
  '/api/categories': typeof ApiCategoriesIndexRoute
  '/api/items': typeof ApiItemsIndexRoute
  '/api/lists': typeof ApiListsIndexRoute
  '/api/purchases': typeof ApiPurchasesIndexRoute
  '/api/lists/items/add': typeof ApiListsItemsAddRoute
  '/api/lists/items': typeof ApiListsItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/items': typeof ItemsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/lists/': typeof ListsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/catalog/categories': typeof ApiCatalogCategoriesRoute
  '/api/catalog/items': typeof ApiCatalogItemsRoute
  '/api/catalog/price': typeof ApiCatalogPriceRoute
  '/api/categories/$': typeof ApiCategoriesSplatRoute
  '/api/items/$': typeof ApiItemsSplatRoute
  '/api/lists/$': typeof ApiListsSplatRoute
  '/api/locations/cities': typeof ApiLocationsCitiesRoute
  '/api/locations/provinces': typeof ApiLocationsProvincesRoute
  '/api/user/location': typeof ApiUserLocationRoute
  '/api/categories/': typeof ApiCategoriesIndexRoute
  '/api/items/': typeof ApiItemsIndexRoute
  '/api/lists/': typeof ApiListsIndexRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/lists/items/add': typeof ApiListsItemsAddRoute
  '/api/lists/items/': typeof ApiListsItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/items'
    | '/login'
    | '/settings'
    | '/signup'
    | '/lists/$listId'
    | '/lists/'
    | '/api/auth/$'
    | '/api/catalog/categories'
    | '/api/catalog/items'
    | '/api/catalog/price'
    | '/api/categories/$'
    | '/api/items/$'
    | '/api/lists/$'
    | '/api/locations/cities'
    | '/api/locations/provinces'
    | '/api/user/location'
    | '/api/categories/'
    | '/api/items/'
    | '/api/lists/'
    | '/api/purchases/'
    | '/api/lists/items/add'
    | '/api/lists/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/items'
    | '/login'
    | '/settings'
    | '/signup'
    | '/lists/$listId'
    | '/lists'
    | '/api/auth/$'
    | '/api/catalog/categories'
    | '/api/catalog/items'
    | '/api/catalog/price'
    | '/api/categories/$'
    | '/api/items/$'
    | '/api/lists/$'
    | '/api/locations/cities'
    | '/api/locations/provinces'
    | '/api/user/location'
    | '/api/categories'
    | '/api/items'
    | '/api/lists'
    | '/api/purchases'
    | '/api/lists/items/add'
    | '/api/lists/items'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/items'
    | '/login'
    | '/settings'
    | '/signup'
    | '/lists/$listId'
    | '/lists/'
    | '/api/auth/$'
    | '/api/catalog/categories'
    | '/api/catalog/items'
    | '/api/catalog/price'
    | '/api/categories/$'
    | '/api/items/$'
    | '/api/lists/$'
    | '/api/locations/cities'
    | '/api/locations/provinces'
    | '/api/user/location'
    | '/api/categories/'
    | '/api/items/'
    | '/api/lists/'
    | '/api/purchases/'
    | '/api/lists/items/add'
    | '/api/lists/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ItemsRoute: typeof ItemsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ListsListIdRoute: typeof ListsListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCatalogCategoriesRoute: typeof ApiCatalogCategoriesRoute
  ApiCatalogItemsRoute: typeof ApiCatalogItemsRoute
  ApiCatalogPriceRoute: typeof ApiCatalogPriceRoute
  ApiCategoriesSplatRoute: typeof ApiCategoriesSplatRoute
  ApiItemsSplatRoute: typeof ApiItemsSplatRoute
  ApiListsSplatRoute: typeof ApiListsSplatRoute
  ApiLocationsCitiesRoute: typeof ApiLocationsCitiesRoute
  ApiLocationsProvincesRoute: typeof ApiLocationsProvincesRoute
  ApiUserLocationRoute: typeof ApiUserLocationRoute
  ApiCategoriesIndexRoute: typeof ApiCategoriesIndexRoute
  ApiItemsIndexRoute: typeof ApiItemsIndexRoute
  ApiListsIndexRoute: typeof ApiListsIndexRoute
  ApiPurchasesIndexRoute: typeof ApiPurchasesIndexRoute
  ApiListsItemsAddRoute: typeof ApiListsItemsAddRoute
  ApiListsItemsIndexRoute: typeof ApiListsItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchases/': {
      id: '/api/purchases/'
      path: '/api/purchases'
      fullPath: '/api/purchases/'
      preLoaderRoute: typeof ApiPurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/': {
      id: '/api/lists/'
      path: '/api/lists'
      fullPath: '/api/lists/'
      preLoaderRoute: typeof ApiListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/': {
      id: '/api/items/'
      path: '/api/items'
      fullPath: '/api/items/'
      preLoaderRoute: typeof ApiItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/': {
      id: '/api/categories/'
      path: '/api/categories'
      fullPath: '/api/categories/'
      preLoaderRoute: typeof ApiCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/location': {
      id: '/api/user/location'
      path: '/api/user/location'
      fullPath: '/api/user/location'
      preLoaderRoute: typeof ApiUserLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/provinces': {
      id: '/api/locations/provinces'
      path: '/api/locations/provinces'
      fullPath: '/api/locations/provinces'
      preLoaderRoute: typeof ApiLocationsProvincesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locations/cities': {
      id: '/api/locations/cities'
      path: '/api/locations/cities'
      fullPath: '/api/locations/cities'
      preLoaderRoute: typeof ApiLocationsCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/$': {
      id: '/api/lists/$'
      path: '/api/lists/$'
      fullPath: '/api/lists/$'
      preLoaderRoute: typeof ApiListsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$': {
      id: '/api/items/$'
      path: '/api/items/$'
      fullPath: '/api/items/$'
      preLoaderRoute: typeof ApiItemsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories/$': {
      id: '/api/categories/$'
      path: '/api/categories/$'
      fullPath: '/api/categories/$'
      preLoaderRoute: typeof ApiCategoriesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/price': {
      id: '/api/catalog/price'
      path: '/api/catalog/price'
      fullPath: '/api/catalog/price'
      preLoaderRoute: typeof ApiCatalogPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/items': {
      id: '/api/catalog/items'
      path: '/api/catalog/items'
      fullPath: '/api/catalog/items'
      preLoaderRoute: typeof ApiCatalogItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/categories': {
      id: '/api/catalog/categories'
      path: '/api/catalog/categories'
      fullPath: '/api/catalog/categories'
      preLoaderRoute: typeof ApiCatalogCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/items/': {
      id: '/api/lists/items/'
      path: '/api/lists/items'
      fullPath: '/api/lists/items/'
      preLoaderRoute: typeof ApiListsItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lists/items/add': {
      id: '/api/lists/items/add'
      path: '/api/lists/items/add'
      fullPath: '/api/lists/items/add'
      preLoaderRoute: typeof ApiListsItemsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ItemsRoute: ItemsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ListsListIdRoute: ListsListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCatalogCategoriesRoute: ApiCatalogCategoriesRoute,
  ApiCatalogItemsRoute: ApiCatalogItemsRoute,
  ApiCatalogPriceRoute: ApiCatalogPriceRoute,
  ApiCategoriesSplatRoute: ApiCategoriesSplatRoute,
  ApiItemsSplatRoute: ApiItemsSplatRoute,
  ApiListsSplatRoute: ApiListsSplatRoute,
  ApiLocationsCitiesRoute: ApiLocationsCitiesRoute,
  ApiLocationsProvincesRoute: ApiLocationsProvincesRoute,
  ApiUserLocationRoute: ApiUserLocationRoute,
  ApiCategoriesIndexRoute: ApiCategoriesIndexRoute,
  ApiItemsIndexRoute: ApiItemsIndexRoute,
  ApiListsIndexRoute: ApiListsIndexRoute,
  ApiPurchasesIndexRoute: ApiPurchasesIndexRoute,
  ApiListsItemsAddRoute: ApiListsItemsAddRoute,
  ApiListsItemsIndexRoute: ApiListsItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
